/**
 * Medical Knowledge Base for RAG.
 * Loads CDC/WHO STI guideline chunks from rag_chunks.json (built by
 * data_processing/chunk_pdfs.py) and searches them by keyword overlap.
 *
 * The chunks live at data/rag_chunks.json (~34k entries; generated by data_processing/build_rag.py).
 * They are read once at module load and cached for the process lifetime.
 */

import fs from 'fs';
import path from 'path';
import { ragScrubEnabled } from '@/lib/feature-flags';
import { scrubForStorage } from './scrub';

interface RagChunk {
  source: string;
  text: string;
  patient_id?: string;
}

interface ScoredChunk {
  chunk: RagChunk;
  score: number;
}

// Resolve relative to the repo root regardless of where Next.js runs from.
const RAG_CHUNKS_PATH = path.resolve(process.cwd(), '../../data/rag_chunks.json');

let _chunks: RagChunk[] | null = null;

// In-memory corpus of live user conversations. Grows as patients chat.
// Stored on `global` so all Next.js route bundles share the same array
// (each route is a separate webpack bundle in dev mode).
declare global {
  // eslint-disable-next-line no-var
  var __userConversationChunks: RagChunk[] | undefined;
}
if (!global.__userConversationChunks) {
  global.__userConversationChunks = [];
}
const _userConversationChunks = global.__userConversationChunks;

export async function addUserConversationChunk(
  userId: string,
  userMessage: string,
  assistantResponse: string,
): Promise<void> {
  let text: string;

  if (ragScrubEnabled()) {
    try {
      const summary = await scrubForStorage(userMessage, assistantResponse);
      text = `De-identified patient experience: ${summary}`;
    } catch (err) {
      // Fail-closed: could not de-identify → drop the turn, store nothing.
      // A privacy control must never persist un-de-identified content.
      console.warn(
        `[RAG] Scrub failed for user=${userId}; dropping turn (fail-closed): ${err}`,
      );
      return;
    }
  } else {
    text = `Patient message: ${userMessage}\nAssistant response: ${assistantResponse}`;
  }

  _userConversationChunks.push({
    source: 'user_conversation',
    text,
    patient_id: userId,
  });
  console.log(
    `[RAG] Added conversation chunk for user=${userId} (scrub=${ragScrubEnabled()}). ` +
    `Total live chunks: ${_userConversationChunks.length}`,
  );
}

function loadChunks(): RagChunk[] {
  if (_chunks) return _chunks;
  try {
    const raw = fs.readFileSync(RAG_CHUNKS_PATH, 'utf-8');
    _chunks = JSON.parse(raw) as RagChunk[];
    console.log(`[RAG] Loaded ${_chunks.length} chunks from ${RAG_CHUNKS_PATH}`);
  } catch (err) {
    console.warn(`[RAG] Could not load rag_chunks.json: ${err}. Falling back to empty corpus.`);
    _chunks = [];
  }
  return _chunks;
}

/**
 * Score a chunk against a query using word-overlap.
 * Longer matching words score higher; stop-words (<4 chars) are skipped.
 */
function scoreChunk(chunk: RagChunk, queryWords: string[]): number {
  const text = chunk.text.toLowerCase();
  let score = 0;
  for (const word of queryWords) {
    if (word.length < 4) continue;
    if (text.includes(word)) {
      score += word.length;
    }
  }
  return score;
}

export function searchMedicalKB(query: string, topN: number = 3): { topic: string; context: string }[] {
  // Search both static corpus and live user conversation chunks.
  const chunks = [...loadChunks(), ..._userConversationChunks];
  if (chunks.length === 0) return [];

  const queryWords = query.toLowerCase().split(/\s+/);

  const scored: ScoredChunk[] = chunks
    .map((chunk) => ({ chunk, score: scoreChunk(chunk, queryWords) }))
    .filter((s) => s.score > 0);

  scored.sort((a, b) => b.score - a.score);

  return scored.slice(0, topN).map((s) => ({
    topic: s.chunk.source.replace(/_/g, ' ').replace('.pdf', ''),
    context: s.chunk.text,
  }));
}

export function buildRAGContext(query: string): string {
  const results = searchMedicalKB(query);
  if (results.length === 0) return '';

  const staticResults  = results.filter((r) => r.topic !== 'user conversation');
  const liveResults    = results.filter((r) => r.topic === 'user conversation');

  const parts: string[] = [];

  if (staticResults.length > 0) {
    parts.push(
      `Relevant medical guidelines:\n` +
      staticResults.map((r) => `[${r.topic}]: ${r.context}`).join('\n\n'),
    );
  }

  if (liveResults.length > 0) {
    parts.push(
      `Related experiences shared by other patients on this platform:\n` +
      liveResults.map((r) => r.context).join('\n\n') +
      `\n\nWhere relevant, draw on these experiences to offer empathy and help the current patient feel they are not alone.`,
    );
  }

  return `\n\n${parts.join('\n\n')}\n\nUse the above to inform your response.`;
}
