"""
build_rag.py — Build the Mercury RAG corpus from all source data.

This script consolidates two knowledge sources into a single rag_chunks.json:

  Source 1: Clinical guidelines (CDC + WHO)
    - PDFs in data/rag_docs/
    - Split into 500-char chunks with 50-char overlap (LangChain splitter)
    - Authoritative, evidence-based clinical content

  Source 2: STD Q&A conversations (ruslanmv/ai-medical-chatbot dataset)
    - data/std_conversations.csv (generated by filter_conversations.py)
    - Filtered for quality before inclusion (see CURATION DECISIONS below)
    - Covers conversational language patients actually use

CURATION DECISIONS (documented for Responsible AI transparency):
  - Dropped answers shorter than 100 characters: too brief to be informative
  - Dropped responses that are purely boilerplate ("please consult your doctor"
    with no medical content): misleading to include as medical knowledge
  - Dropped questions shorter than 20 characters: too vague to be useful
  - Kept duplicate topics: slight redundancy helps retrieval coverage

OUTPUT:
  data/rag_chunks.json — 34k+ chunks, ready for keyword or semantic search

USAGE:
  cd data_processing/
  pip install -r requirements.txt
  python filter_conversations.py   # downloads dataset, creates std_conversations.csv
  python build_rag.py              # creates rag_chunks.json
"""

import json
import os
import csv

# ── Paths ────────────────────────────────────────────────────────────────────
BASE_DIR       = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PDF_DIR        = os.path.join(BASE_DIR, "data", "rag_docs")
CONVERSATIONS  = os.path.join(BASE_DIR, "data", "std_conversations.csv")
OUTPUT         = os.path.join(BASE_DIR, "data", "rag_chunks.json")

# ── Chunk size (characters) ──────────────────────────────────────────────────
CHUNK_SIZE    = 500
CHUNK_OVERLAP = 50


# ── Step 1: PDF guidelines ───────────────────────────────────────────────────

def load_pdf_chunks() -> list[dict]:
    """
    Load and chunk all PDFs from data/rag_docs/.
    Requires: langchain-community, pypdf
    """
    try:
        from langchain_community.document_loaders import PyPDFLoader
        from langchain_text_splitters import RecursiveCharacterTextSplitter
    except ImportError:
        print("  [skip] langchain not installed — skipping PDF chunking.")
        print("         Run: pip install langchain-community langchain-text-splitters pypdf")
        return []

    if not os.path.isdir(PDF_DIR):
        print(f"  [skip] PDF directory not found: {PDF_DIR}")
        print("         Place CDC/WHO STI guideline PDFs in data/rag_docs/ and re-run.")
        return []

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=CHUNK_SIZE,
        chunk_overlap=CHUNK_OVERLAP,
    )

    chunks = []
    pdfs = [f for f in os.listdir(PDF_DIR) if f.endswith(".pdf")]
    if not pdfs:
        print(f"  [skip] No PDFs found in {PDF_DIR}")
        return []

    for filename in pdfs:
        loader = PyPDFLoader(os.path.join(PDF_DIR, filename))
        pages = loader.load()
        split = splitter.split_documents(pages)
        for doc in split:
            chunks.append({"source": filename, "text": doc.page_content})
        print(f"  {filename}: {len(split)} chunks")

    return chunks


# ── Step 2: Q&A conversations ────────────────────────────────────────────────

# Phrases that indicate a response contains no actual medical information.
_BOILERPLATE = [
    "do not hesitate to ask",
    "hope your query is answered",
    "please consult your doctor",
    "best wishes",
]


def is_useful(question: str, answer: str) -> bool:
    """
    Return True if this Q&A pair is worth including in the RAG corpus.

    Curation rules (each exclusion is deliberate — see module docstring):
      1. Answer too short to contain real information.
      2. Short answer that is mostly boilerplate phrases.
      3. Question too vague to help retrieval.
    """
    if len(answer) < 100:
        return False

    lower = answer.lower()
    if len(answer) < 200 and sum(1 for b in _BOILERPLATE if b in lower) >= 2:
        return False

    if len(question) < 20:
        return False

    return True


def load_conversation_chunks() -> list[dict]:
    """
    Load Q&A conversations from std_conversations.csv, apply quality filters,
    and return as RAG chunks.
    """
    if not os.path.exists(CONVERSATIONS):
        print(f"  [skip] {CONVERSATIONS} not found.")
        print("         Run filter_conversations.py first to generate it.")
        return []

    chunks = []
    dropped = 0

    with open(CONVERSATIONS, encoding="utf-8") as f:
        for row in csv.DictReader(f):
            question = row.get("Description", "").strip()
            answer   = row.get("Doctor", "").strip()

            if not is_useful(question, answer):
                dropped += 1
                continue

            chunks.append({
                "source": "std_qa_conversations",
                "text": f"Patient question: {question}\nDoctor answer: {answer}",
            })

    print(f"  std_conversations.csv: {len(chunks)} kept, {dropped} dropped")
    return chunks


# ── Main ─────────────────────────────────────────────────────────────────────

def main():
    print("Building RAG corpus...")
    print()

    print("Step 1: Clinical guidelines (PDFs)")
    pdf_chunks = load_pdf_chunks()
    print(f"  → {len(pdf_chunks)} guideline chunks")
    print()

    print("Step 2: STD Q&A conversations")
    qa_chunks = load_conversation_chunks()
    print(f"  → {len(qa_chunks)} conversation chunks")
    print()

    all_chunks = pdf_chunks + qa_chunks

    with open(OUTPUT, "w") as f:
        json.dump(all_chunks, f, indent=2)

    print(f"Saved {len(all_chunks):,} total chunks → {OUTPUT}")
    print()
    print("Breakdown by source:")
    sources: dict[str, int] = {}
    for c in all_chunks:
        sources[c["source"]] = sources.get(c["source"], 0) + 1
    for src, count in sorted(sources.items(), key=lambda x: -x[1]):
        print(f"  {src}: {count:,}")


if __name__ == "__main__":
    main()
